/********************************************************************************
** Form generated from reading UI file 'primapag.ui'
**
** Created by: Qt User Interface Compiler version 6.3.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PRIMAPAG_H
#define UI_PRIMAPAG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_PrimaPag
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *p1_logare;
    QLineEdit *username;
    QLineEdit *parola;
    QLabel *l_username;
    QLabel *l_intro;
    QLabel *l_parola;
    QPushButton *autentificare;
    QLabel *l;
    QPushButton *inregistrare;
    QPushButton *sch_parola;
    QWidget *p_mesaj_cerere;
    QLabel *label_4;
    QPushButton *spre_autentificare;
    QWidget *p_sch_parola;
    QLineEdit *email_2;
    QLabel *label;
    QLabel *label_2;
    QPushButton *sch_parola_2;
    QLineEdit *parola_4;
    QLabel *label_3;
    QWidget *p3_inregistrare;
    QLineEdit *username_3;
    QLineEdit *parola_3;
    QLineEdit *nume;
    QLineEdit *prenume;
    QLineEdit *email;
    QLabel *l_user;
    QLabel *l_parola_3;
    QLabel *l_nume;
    QLabel *l_prenume;
    QLabel *l_email;
    QLabel *l_telefon;
    QLineEdit *telefon;
    QPushButton *inregistrare_2;
    QWidget *p2_client;
    QLabel *us_pag_client;
    QTabWidget *tabWidget;
    QWidget *pag_client;
    QPushButton *apel_112;
    QPushButton *apel_politie;
    QPushButton *apel_pompieri;
    QPushButton *apel_salvamont;
    QPushButton *apel_ambulanta;
    QPushButton *apel_jandarmerie;
    QPushButton *apel_smurd;
    QLabel *label_5;
    QWidget *istoric_ap_client;
    QTableWidget *tbl_istoric_client;
    QPushButton *delog_cl;
    QWidget *p_dispecer;
    QTabWidget *tab_dispecer;
    QWidget *detalii;
    QListWidget *lista_in_astp;
    QPushButton *add_descriere;
    QWidget *istoric_dispecer;
    QTableWidget *tbl_istoric_dispecer;
    QWidget *utilizatori;
    QListWidget *list_utilizatori;
    QLabel *l_utilizatori;
    QPushButton *but_inf;
    QPushButton *but_stergere;
    QLabel *label_6;
    QLabel *u_pag_dis;
    QPushButton *delog_disp;
    QWidget *p_administrator;
    QTabWidget *tab_admin;
    QWidget *istoric_administrator;
    QListWidget *lista_ist_apeluri_adm;
    QPushButton *b_inf_apel;
    QPushButton *b_sterg_apel;
    QPushButton *b_sterg_istoric;
    QWidget *utilizatori_2;
    QListWidget *list_utilizatori_2;
    QLabel *l_utilizatori_2;
    QPushButton *but_inf_2;
    QPushButton *but_stergere_2;
    QWidget *dispeceri;
    QListWidget *lista_dispeceri;
    QPushButton *b_inf_disp;
    QPushButton *b_stergere_disp;
    QPushButton *b_add_disp;
    QWidget *cereri_inregistrari;
    QListWidget *lista_cereri_inrg;
    QPushButton *inf_inrg;
    QPushButton *aprob_inrg;
    QPushButton *resping_inreg;
    QWidget *cereri_stergeri;
    QListWidget *lista_cereri_st;
    QPushButton *aprob_strg;
    QPushButton *resping_strg;
    QPushButton *inf_strg;
    QLabel *label_7;
    QPushButton *delog_adm;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *PrimaPag)
    {
        if (PrimaPag->objectName().isEmpty())
            PrimaPag->setObjectName(QString::fromUtf8("PrimaPag"));
        PrimaPag->resize(700, 551);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(PrimaPag->sizePolicy().hasHeightForWidth());
        PrimaPag->setSizePolicy(sizePolicy);
        PrimaPag->setMinimumSize(QSize(700, 500));
        centralwidget = new QWidget(PrimaPag);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setMinimumSize(QSize(700, 500));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 700, 500));
        QFont font;
        font.setPointSize(9);
        stackedWidget->setFont(font);
        p1_logare = new QWidget();
        p1_logare->setObjectName(QString::fromUtf8("p1_logare"));
        username = new QLineEdit(p1_logare);
        username->setObjectName(QString::fromUtf8("username"));
        username->setGeometry(QRect(70, 170, 161, 31));
        parola = new QLineEdit(p1_logare);
        parola->setObjectName(QString::fromUtf8("parola"));
        parola->setGeometry(QRect(70, 260, 161, 31));
        parola->setEchoMode(QLineEdit::Password);
        l_username = new QLabel(p1_logare);
        l_username->setObjectName(QString::fromUtf8("l_username"));
        l_username->setGeometry(QRect(70, 140, 81, 31));
        l_intro = new QLabel(p1_logare);
        l_intro->setObjectName(QString::fromUtf8("l_intro"));
        l_intro->setGeometry(QRect(60, 50, 471, 71));
        QFont font1;
        font1.setPointSize(13);
        font1.setBold(true);
        font1.setItalic(true);
        l_intro->setFont(font1);
        l_parola = new QLabel(p1_logare);
        l_parola->setObjectName(QString::fromUtf8("l_parola"));
        l_parola->setGeometry(QRect(70, 230, 81, 31));
        autentificare = new QPushButton(p1_logare);
        autentificare->setObjectName(QString::fromUtf8("autentificare"));
        autentificare->setGeometry(QRect(80, 310, 141, 41));
        autentificare->setStyleSheet(QString::fromUtf8("background: rgb(183, 227, 255)"));
        l = new QLabel(p1_logare);
        l->setObjectName(QString::fromUtf8("l"));
        l->setGeometry(QRect(90, 390, 81, 31));
        inregistrare = new QPushButton(p1_logare);
        inregistrare->setObjectName(QString::fromUtf8("inregistrare"));
        inregistrare->setGeometry(QRect(170, 390, 111, 31));
        QFont font2;
        font2.setPointSize(9);
        font2.setItalic(true);
        font2.setUnderline(true);
        inregistrare->setFont(font2);
        inregistrare->setCursor(QCursor(Qt::PointingHandCursor));
        inregistrare->setStyleSheet(QString::fromUtf8("color: green"));
        inregistrare->setFlat(true);
        sch_parola = new QPushButton(p1_logare);
        sch_parola->setObjectName(QString::fromUtf8("sch_parola"));
        sch_parola->setGeometry(QRect(90, 420, 141, 31));
        sch_parola->setFont(font2);
        sch_parola->setCursor(QCursor(Qt::PointingHandCursor));
        sch_parola->setStyleSheet(QString::fromUtf8("color: green"));
        sch_parola->setFlat(true);
        stackedWidget->addWidget(p1_logare);
        p_mesaj_cerere = new QWidget();
        p_mesaj_cerere->setObjectName(QString::fromUtf8("p_mesaj_cerere"));
        label_4 = new QLabel(p_mesaj_cerere);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(160, 190, 381, 61));
        QFont font3;
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setItalic(true);
        label_4->setFont(font3);
        spre_autentificare = new QPushButton(p_mesaj_cerere);
        spre_autentificare->setObjectName(QString::fromUtf8("spre_autentificare"));
        spre_autentificare->setGeometry(QRect(500, 430, 181, 41));
        spre_autentificare->setStyleSheet(QString::fromUtf8("background: rgb(235, 176, 255)"));
        stackedWidget->addWidget(p_mesaj_cerere);
        p_sch_parola = new QWidget();
        p_sch_parola->setObjectName(QString::fromUtf8("p_sch_parola"));
        email_2 = new QLineEdit(p_sch_parola);
        email_2->setObjectName(QString::fromUtf8("email_2"));
        email_2->setGeometry(QRect(90, 230, 181, 31));
        label = new QLabel(p_sch_parola);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(90, 199, 63, 31));
        label_2 = new QLabel(p_sch_parola);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(40, 100, 291, 91));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        label_2->setFont(font4);
        sch_parola_2 = new QPushButton(p_sch_parola);
        sch_parola_2->setObjectName(QString::fromUtf8("sch_parola_2"));
        sch_parola_2->setGeometry(QRect(220, 360, 141, 31));
        sch_parola_2->setStyleSheet(QString::fromUtf8("background: rgb(255, 249, 180)"));
        parola_4 = new QLineEdit(p_sch_parola);
        parola_4->setObjectName(QString::fromUtf8("parola_4"));
        parola_4->setGeometry(QRect(90, 310, 181, 31));
        parola_4->setEchoMode(QLineEdit::Password);
        label_3 = new QLabel(p_sch_parola);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(90, 285, 91, 21));
        stackedWidget->addWidget(p_sch_parola);
        p3_inregistrare = new QWidget();
        p3_inregistrare->setObjectName(QString::fromUtf8("p3_inregistrare"));
        username_3 = new QLineEdit(p3_inregistrare);
        username_3->setObjectName(QString::fromUtf8("username_3"));
        username_3->setGeometry(QRect(160, 70, 181, 31));
        parola_3 = new QLineEdit(p3_inregistrare);
        parola_3->setObjectName(QString::fromUtf8("parola_3"));
        parola_3->setGeometry(QRect(160, 120, 181, 31));
        parola_3->setEchoMode(QLineEdit::Password);
        nume = new QLineEdit(p3_inregistrare);
        nume->setObjectName(QString::fromUtf8("nume"));
        nume->setGeometry(QRect(160, 170, 181, 31));
        prenume = new QLineEdit(p3_inregistrare);
        prenume->setObjectName(QString::fromUtf8("prenume"));
        prenume->setGeometry(QRect(160, 220, 181, 31));
        email = new QLineEdit(p3_inregistrare);
        email->setObjectName(QString::fromUtf8("email"));
        email->setGeometry(QRect(160, 270, 181, 31));
        l_user = new QLabel(p3_inregistrare);
        l_user->setObjectName(QString::fromUtf8("l_user"));
        l_user->setGeometry(QRect(80, 70, 71, 21));
        l_parola_3 = new QLabel(p3_inregistrare);
        l_parola_3->setObjectName(QString::fromUtf8("l_parola_3"));
        l_parola_3->setGeometry(QRect(80, 120, 71, 21));
        l_nume = new QLabel(p3_inregistrare);
        l_nume->setObjectName(QString::fromUtf8("l_nume"));
        l_nume->setGeometry(QRect(80, 170, 71, 21));
        l_prenume = new QLabel(p3_inregistrare);
        l_prenume->setObjectName(QString::fromUtf8("l_prenume"));
        l_prenume->setGeometry(QRect(80, 220, 81, 21));
        l_email = new QLabel(p3_inregistrare);
        l_email->setObjectName(QString::fromUtf8("l_email"));
        l_email->setGeometry(QRect(80, 270, 71, 21));
        l_telefon = new QLabel(p3_inregistrare);
        l_telefon->setObjectName(QString::fromUtf8("l_telefon"));
        l_telefon->setGeometry(QRect(80, 320, 71, 21));
        telefon = new QLineEdit(p3_inregistrare);
        telefon->setObjectName(QString::fromUtf8("telefon"));
        telefon->setGeometry(QRect(160, 320, 181, 31));
        inregistrare_2 = new QPushButton(p3_inregistrare);
        inregistrare_2->setObjectName(QString::fromUtf8("inregistrare_2"));
        inregistrare_2->setGeometry(QRect(300, 370, 93, 29));
        inregistrare_2->setStyleSheet(QString::fromUtf8("background: rgb(187, 255, 144)"));
        stackedWidget->addWidget(p3_inregistrare);
        p2_client = new QWidget();
        p2_client->setObjectName(QString::fromUtf8("p2_client"));
        us_pag_client = new QLabel(p2_client);
        us_pag_client->setObjectName(QString::fromUtf8("us_pag_client"));
        us_pag_client->setGeometry(QRect(570, 10, 111, 20));
        tabWidget = new QTabWidget(p2_client);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 10, 711, 491));
        pag_client = new QWidget();
        pag_client->setObjectName(QString::fromUtf8("pag_client"));
        apel_112 = new QPushButton(pag_client);
        apel_112->setObjectName(QString::fromUtf8("apel_112"));
        apel_112->setGeometry(QRect(280, 110, 91, 51));
        QFont font5;
        font5.setPointSize(11);
        apel_112->setFont(font5);
        apel_112->setStyleSheet(QString::fromUtf8("background: red"));
        apel_politie = new QPushButton(pag_client);
        apel_politie->setObjectName(QString::fromUtf8("apel_politie"));
        apel_politie->setGeometry(QRect(80, 250, 81, 41));
        apel_politie->setFont(font5);
        apel_politie->setStyleSheet(QString::fromUtf8("background: white;\n"
"border-color: rgb(255, 170, 0);"));
        apel_pompieri = new QPushButton(pag_client);
        apel_pompieri->setObjectName(QString::fromUtf8("apel_pompieri"));
        apel_pompieri->setGeometry(QRect(280, 250, 101, 41));
        apel_pompieri->setFont(font5);
        apel_pompieri->setStyleSheet(QString::fromUtf8("background: white"));
        apel_salvamont = new QPushButton(pag_client);
        apel_salvamont->setObjectName(QString::fromUtf8("apel_salvamont"));
        apel_salvamont->setGeometry(QRect(450, 250, 131, 41));
        apel_salvamont->setFont(font5);
        apel_salvamont->setStyleSheet(QString::fromUtf8("background: white"));
        apel_ambulanta = new QPushButton(pag_client);
        apel_ambulanta->setObjectName(QString::fromUtf8("apel_ambulanta"));
        apel_ambulanta->setGeometry(QRect(60, 360, 121, 41));
        apel_ambulanta->setFont(font5);
        apel_ambulanta->setStyleSheet(QString::fromUtf8("background: white\n"
""));
        apel_jandarmerie = new QPushButton(pag_client);
        apel_jandarmerie->setObjectName(QString::fromUtf8("apel_jandarmerie"));
        apel_jandarmerie->setGeometry(QRect(450, 360, 131, 41));
        apel_jandarmerie->setFont(font5);
        apel_jandarmerie->setStyleSheet(QString::fromUtf8("background: white"));
        apel_smurd = new QPushButton(pag_client);
        apel_smurd->setObjectName(QString::fromUtf8("apel_smurd"));
        apel_smurd->setGeometry(QRect(290, 360, 81, 41));
        apel_smurd->setFont(font5);
        apel_smurd->setStyleSheet(QString::fromUtf8("background: white"));
        label_5 = new QLabel(pag_client);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(90, 220, 601, 20));
        QFont font6;
        font6.setPointSize(9);
        font6.setItalic(true);
        label_5->setFont(font6);
        tabWidget->addTab(pag_client, QString());
        istoric_ap_client = new QWidget();
        istoric_ap_client->setObjectName(QString::fromUtf8("istoric_ap_client"));
        tbl_istoric_client = new QTableWidget(istoric_ap_client);
        if (tbl_istoric_client->columnCount() < 2)
            tbl_istoric_client->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tbl_istoric_client->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tbl_istoric_client->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        tbl_istoric_client->setObjectName(QString::fromUtf8("tbl_istoric_client"));
        tbl_istoric_client->setGeometry(QRect(0, 0, 691, 451));
        tbl_istoric_client->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tbl_istoric_client->setRowCount(0);
        tabWidget->addTab(istoric_ap_client, QString());
        delog_cl = new QPushButton(p2_client);
        delog_cl->setObjectName(QString::fromUtf8("delog_cl"));
        delog_cl->setGeometry(QRect(630, 10, 21, 21));
        delog_cl->setStyleSheet(QString::fromUtf8("background: red"));
        stackedWidget->addWidget(p2_client);
        p_dispecer = new QWidget();
        p_dispecer->setObjectName(QString::fromUtf8("p_dispecer"));
        tab_dispecer = new QTabWidget(p_dispecer);
        tab_dispecer->setObjectName(QString::fromUtf8("tab_dispecer"));
        tab_dispecer->setGeometry(QRect(0, 10, 701, 491));
        detalii = new QWidget();
        detalii->setObjectName(QString::fromUtf8("detalii"));
        lista_in_astp = new QListWidget(detalii);
        lista_in_astp->setObjectName(QString::fromUtf8("lista_in_astp"));
        lista_in_astp->setGeometry(QRect(15, 11, 391, 411));
        add_descriere = new QPushButton(detalii);
        add_descriere->setObjectName(QString::fromUtf8("add_descriere"));
        add_descriere->setGeometry(QRect(520, 180, 93, 71));
        tab_dispecer->addTab(detalii, QString());
        istoric_dispecer = new QWidget();
        istoric_dispecer->setObjectName(QString::fromUtf8("istoric_dispecer"));
        tbl_istoric_dispecer = new QTableWidget(istoric_dispecer);
        if (tbl_istoric_dispecer->columnCount() < 3)
            tbl_istoric_dispecer->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tbl_istoric_dispecer->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tbl_istoric_dispecer->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tbl_istoric_dispecer->setHorizontalHeaderItem(2, __qtablewidgetitem4);
        tbl_istoric_dispecer->setObjectName(QString::fromUtf8("tbl_istoric_dispecer"));
        tbl_istoric_dispecer->setGeometry(QRect(5, 1, 681, 461));
        tbl_istoric_dispecer->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        tbl_istoric_dispecer->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tbl_istoric_dispecer->setRowCount(0);
        tbl_istoric_dispecer->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        tbl_istoric_dispecer->horizontalHeader()->setStretchLastSection(true);
        tab_dispecer->addTab(istoric_dispecer, QString());
        utilizatori = new QWidget();
        utilizatori->setObjectName(QString::fromUtf8("utilizatori"));
        list_utilizatori = new QListWidget(utilizatori);
        list_utilizatori->setObjectName(QString::fromUtf8("list_utilizatori"));
        list_utilizatori->setGeometry(QRect(5, 31, 301, 421));
        list_utilizatori->setEditTriggers(QAbstractItemView::NoEditTriggers);
        l_utilizatori = new QLabel(utilizatori);
        l_utilizatori->setObjectName(QString::fromUtf8("l_utilizatori"));
        l_utilizatori->setGeometry(QRect(20, 10, 151, 20));
        but_inf = new QPushButton(utilizatori);
        but_inf->setObjectName(QString::fromUtf8("but_inf"));
        but_inf->setGeometry(QRect(450, 80, 93, 29));
        but_stergere = new QPushButton(utilizatori);
        but_stergere->setObjectName(QString::fromUtf8("but_stergere"));
        but_stergere->setGeometry(QRect(430, 300, 131, 29));
        tab_dispecer->addTab(utilizatori, QString());
        list_utilizatori->raise();
        l_utilizatori->raise();
        but_stergere->raise();
        but_inf->raise();
        label_6 = new QLabel(p_dispecer);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(490, 10, 63, 20));
        u_pag_dis = new QLabel(p_dispecer);
        u_pag_dis->setObjectName(QString::fromUtf8("u_pag_dis"));
        u_pag_dis->setGeometry(QRect(560, 10, 131, 20));
        delog_disp = new QPushButton(p_dispecer);
        delog_disp->setObjectName(QString::fromUtf8("delog_disp"));
        delog_disp->setGeometry(QRect(660, 10, 21, 21));
        delog_disp->setStyleSheet(QString::fromUtf8("background: red"));
        stackedWidget->addWidget(p_dispecer);
        p_administrator = new QWidget();
        p_administrator->setObjectName(QString::fromUtf8("p_administrator"));
        tab_admin = new QTabWidget(p_administrator);
        tab_admin->setObjectName(QString::fromUtf8("tab_admin"));
        tab_admin->setGeometry(QRect(0, 10, 700, 501));
        istoric_administrator = new QWidget();
        istoric_administrator->setObjectName(QString::fromUtf8("istoric_administrator"));
        lista_ist_apeluri_adm = new QListWidget(istoric_administrator);
        lista_ist_apeluri_adm->setObjectName(QString::fromUtf8("lista_ist_apeluri_adm"));
        lista_ist_apeluri_adm->setGeometry(QRect(15, 21, 401, 431));
        b_inf_apel = new QPushButton(istoric_administrator);
        b_inf_apel->setObjectName(QString::fromUtf8("b_inf_apel"));
        b_inf_apel->setGeometry(QRect(490, 80, 141, 29));
        b_inf_apel->setStyleSheet(QString::fromUtf8("background: rgb(181, 191, 255)"));
        b_sterg_apel = new QPushButton(istoric_administrator);
        b_sterg_apel->setObjectName(QString::fromUtf8("b_sterg_apel"));
        b_sterg_apel->setGeometry(QRect(500, 200, 111, 29));
        b_sterg_apel->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        b_sterg_istoric = new QPushButton(istoric_administrator);
        b_sterg_istoric->setObjectName(QString::fromUtf8("b_sterg_istoric"));
        b_sterg_istoric->setGeometry(QRect(480, 400, 161, 29));
        b_sterg_istoric->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        tab_admin->addTab(istoric_administrator, QString());
        utilizatori_2 = new QWidget();
        utilizatori_2->setObjectName(QString::fromUtf8("utilizatori_2"));
        list_utilizatori_2 = new QListWidget(utilizatori_2);
        list_utilizatori_2->setObjectName(QString::fromUtf8("list_utilizatori_2"));
        list_utilizatori_2->setGeometry(QRect(10, 40, 301, 421));
        list_utilizatori_2->setEditTriggers(QAbstractItemView::NoEditTriggers);
        l_utilizatori_2 = new QLabel(utilizatori_2);
        l_utilizatori_2->setObjectName(QString::fromUtf8("l_utilizatori_2"));
        l_utilizatori_2->setGeometry(QRect(20, 20, 151, 20));
        but_inf_2 = new QPushButton(utilizatori_2);
        but_inf_2->setObjectName(QString::fromUtf8("but_inf_2"));
        but_inf_2->setGeometry(QRect(410, 80, 141, 29));
        but_inf_2->setStyleSheet(QString::fromUtf8("background: rgb(181, 191, 255)"));
        but_stergere_2 = new QPushButton(utilizatori_2);
        but_stergere_2->setObjectName(QString::fromUtf8("but_stergere_2"));
        but_stergere_2->setGeometry(QRect(410, 310, 141, 29));
        but_stergere_2->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        tab_admin->addTab(utilizatori_2, QString());
        dispeceri = new QWidget();
        dispeceri->setObjectName(QString::fromUtf8("dispeceri"));
        lista_dispeceri = new QListWidget(dispeceri);
        lista_dispeceri->setObjectName(QString::fromUtf8("lista_dispeceri"));
        lista_dispeceri->setGeometry(QRect(15, 21, 401, 431));
        b_inf_disp = new QPushButton(dispeceri);
        b_inf_disp->setObjectName(QString::fromUtf8("b_inf_disp"));
        b_inf_disp->setGeometry(QRect(480, 100, 151, 29));
        b_inf_disp->setStyleSheet(QString::fromUtf8("background: rgb(181, 191, 255)"));
        b_stergere_disp = new QPushButton(dispeceri);
        b_stergere_disp->setObjectName(QString::fromUtf8("b_stergere_disp"));
        b_stergere_disp->setGeometry(QRect(490, 330, 131, 29));
        b_stergere_disp->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        b_add_disp = new QPushButton(dispeceri);
        b_add_disp->setObjectName(QString::fromUtf8("b_add_disp"));
        b_add_disp->setGeometry(QRect(542, 10, 141, 29));
        b_add_disp->setStyleSheet(QString::fromUtf8("background:rgb(255, 230, 172)"));
        tab_admin->addTab(dispeceri, QString());
        cereri_inregistrari = new QWidget();
        cereri_inregistrari->setObjectName(QString::fromUtf8("cereri_inregistrari"));
        lista_cereri_inrg = new QListWidget(cereri_inregistrari);
        lista_cereri_inrg->setObjectName(QString::fromUtf8("lista_cereri_inrg"));
        lista_cereri_inrg->setGeometry(QRect(20, 20, 441, 431));
        inf_inrg = new QPushButton(cereri_inregistrari);
        inf_inrg->setObjectName(QString::fromUtf8("inf_inrg"));
        inf_inrg->setGeometry(QRect(540, 48, 93, 61));
        inf_inrg->setStyleSheet(QString::fromUtf8("background: rgb(181, 191, 255)"));
        aprob_inrg = new QPushButton(cereri_inregistrari);
        aprob_inrg->setObjectName(QString::fromUtf8("aprob_inrg"));
        aprob_inrg->setGeometry(QRect(540, 260, 93, 29));
        aprob_inrg->setStyleSheet(QString::fromUtf8("background:rgb(165, 255, 165)"));
        resping_inreg = new QPushButton(cereri_inregistrari);
        resping_inreg->setObjectName(QString::fromUtf8("resping_inreg"));
        resping_inreg->setGeometry(QRect(540, 320, 93, 29));
        resping_inreg->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        tab_admin->addTab(cereri_inregistrari, QString());
        cereri_stergeri = new QWidget();
        cereri_stergeri->setObjectName(QString::fromUtf8("cereri_stergeri"));
        lista_cereri_st = new QListWidget(cereri_stergeri);
        lista_cereri_st->setObjectName(QString::fromUtf8("lista_cereri_st"));
        lista_cereri_st->setGeometry(QRect(10, 20, 401, 431));
        aprob_strg = new QPushButton(cereri_stergeri);
        aprob_strg->setObjectName(QString::fromUtf8("aprob_strg"));
        aprob_strg->setGeometry(QRect(510, 340, 93, 29));
        aprob_strg->setStyleSheet(QString::fromUtf8("background:rgb(165, 255, 165)"));
        resping_strg = new QPushButton(cereri_stergeri);
        resping_strg->setObjectName(QString::fromUtf8("resping_strg"));
        resping_strg->setGeometry(QRect(510, 390, 93, 29));
        resping_strg->setStyleSheet(QString::fromUtf8("background: rgb(255, 161, 142)"));
        inf_strg = new QPushButton(cereri_stergeri);
        inf_strg->setObjectName(QString::fromUtf8("inf_strg"));
        inf_strg->setGeometry(QRect(510, 48, 93, 61));
        inf_strg->setStyleSheet(QString::fromUtf8("background: rgb(181, 191, 255)"));
        tab_admin->addTab(cereri_stergeri, QString());
        label_7 = new QLabel(p_administrator);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(510, 10, 101, 20));
        delog_adm = new QPushButton(p_administrator);
        delog_adm->setObjectName(QString::fromUtf8("delog_adm"));
        delog_adm->setGeometry(QRect(630, 10, 21, 21));
        delog_adm->setStyleSheet(QString::fromUtf8("background: red"));
        stackedWidget->addWidget(p_administrator);
        PrimaPag->setCentralWidget(centralwidget);
        menubar = new QMenuBar(PrimaPag);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 700, 22));
        PrimaPag->setMenuBar(menubar);
        statusbar = new QStatusBar(PrimaPag);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        PrimaPag->setStatusBar(statusbar);

        retranslateUi(PrimaPag);

        stackedWidget->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);
        tab_dispecer->setCurrentIndex(2);
        tab_admin->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PrimaPag);
    } // setupUi

    void retranslateUi(QMainWindow *PrimaPag)
    {
        PrimaPag->setWindowTitle(QCoreApplication::translate("PrimaPag", "Apeluri de urgenta", nullptr));
        l_username->setText(QCoreApplication::translate("PrimaPag", "Username", nullptr));
        l_intro->setText(QCoreApplication::translate("PrimaPag", "Bun venit in aplicatia Apeluri de urgenta!", nullptr));
        l_parola->setText(QCoreApplication::translate("PrimaPag", "Parola", nullptr));
        autentificare->setText(QCoreApplication::translate("PrimaPag", "Autentificare", nullptr));
        l->setText(QCoreApplication::translate("PrimaPag", "Nu ai cont? ", nullptr));
        inregistrare->setText(QCoreApplication::translate("PrimaPag", "Inregistraza-te!", nullptr));
        sch_parola->setText(QCoreApplication::translate("PrimaPag", "Mi-am uitat parola!", nullptr));
        label_4->setText(QCoreApplication::translate("PrimaPag", "Cererea dumneavoastra a fost trimisa!", nullptr));
        spre_autentificare->setText(QCoreApplication::translate("PrimaPag", "Inapoi la autentificare", nullptr));
        label->setText(QCoreApplication::translate("PrimaPag", "Email-ul:", nullptr));
        label_2->setText(QCoreApplication::translate("PrimaPag", "Vom trimite in scurt timp un email!", nullptr));
        sch_parola_2->setText(QCoreApplication::translate("PrimaPag", "Trimite cerere", nullptr));
        label_3->setText(QCoreApplication::translate("PrimaPag", "Noua parola:", nullptr));
        l_user->setText(QCoreApplication::translate("PrimaPag", "Username:", nullptr));
        l_parola_3->setText(QCoreApplication::translate("PrimaPag", "Parola:", nullptr));
        l_nume->setText(QCoreApplication::translate("PrimaPag", "Nume:", nullptr));
        l_prenume->setText(QCoreApplication::translate("PrimaPag", "Prenume:", nullptr));
        l_email->setText(QCoreApplication::translate("PrimaPag", "Email:", nullptr));
        l_telefon->setText(QCoreApplication::translate("PrimaPag", "Telefon:", nullptr));
        inregistrare_2->setText(QCoreApplication::translate("PrimaPag", "Inregistrare", nullptr));
        us_pag_client->setText(QCoreApplication::translate("PrimaPag", "User", nullptr));
#if QT_CONFIG(whatsthis)
        tabWidget->setWhatsThis(QString());
#endif // QT_CONFIG(whatsthis)
        apel_112->setText(QCoreApplication::translate("PrimaPag", "112", nullptr));
        apel_politie->setText(QCoreApplication::translate("PrimaPag", "Politie", nullptr));
        apel_pompieri->setText(QCoreApplication::translate("PrimaPag", "Pompieri", nullptr));
        apel_salvamont->setText(QCoreApplication::translate("PrimaPag", "Salvamont", nullptr));
        apel_ambulanta->setText(QCoreApplication::translate("PrimaPag", "Ambulanta", nullptr));
        apel_jandarmerie->setText(QCoreApplication::translate("PrimaPag", "Jandarmerie", nullptr));
        apel_smurd->setText(QCoreApplication::translate("PrimaPag", "Smurd", nullptr));
        label_5->setText(QCoreApplication::translate("PrimaPag", "Stii de ce ai nevoie? Alege tipul echipajului pentru a fi trimis direct la dispecerul specializat!", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(pag_client), QCoreApplication::translate("PrimaPag", "Apelare", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tbl_istoric_client->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("PrimaPag", "            Data si ora          ", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tbl_istoric_client->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("PrimaPag", "Tipul apelului", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(istoric_ap_client), QCoreApplication::translate("PrimaPag", "Istoric apeluri", nullptr));
        delog_cl->setText(QString());
        add_descriere->setText(QCoreApplication::translate("PrimaPag", "Adauga\n"
"descriere", nullptr));
        tab_dispecer->setTabText(tab_dispecer->indexOf(detalii), QCoreApplication::translate("PrimaPag", "In asteptare", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tbl_istoric_dispecer->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("PrimaPag", "username", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tbl_istoric_dispecer->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("PrimaPag", "Data si ora", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tbl_istoric_dispecer->horizontalHeaderItem(2);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("PrimaPag", "Detalii adaugate", nullptr));
        tab_dispecer->setTabText(tab_dispecer->indexOf(istoric_dispecer), QCoreApplication::translate("PrimaPag", "Istoric apeluri", nullptr));
        l_utilizatori->setText(QCoreApplication::translate("PrimaPag", "username utilizatori", nullptr));
        but_inf->setText(QCoreApplication::translate("PrimaPag", "Informatii", nullptr));
        but_stergere->setText(QCoreApplication::translate("PrimaPag", "Cerere stergere", nullptr));
        tab_dispecer->setTabText(tab_dispecer->indexOf(utilizatori), QCoreApplication::translate("PrimaPag", "Utilizatori", nullptr));
        label_6->setText(QCoreApplication::translate("PrimaPag", "Dispecer", nullptr));
        u_pag_dis->setText(QCoreApplication::translate("PrimaPag", "username", nullptr));
        delog_disp->setText(QString());
        b_inf_apel->setText(QCoreApplication::translate("PrimaPag", "Informatii apel", nullptr));
        b_sterg_apel->setText(QCoreApplication::translate("PrimaPag", "Stergere apel", nullptr));
        b_sterg_istoric->setText(QCoreApplication::translate("PrimaPag", "Sterge istoricul", nullptr));
        tab_admin->setTabText(tab_admin->indexOf(istoric_administrator), QCoreApplication::translate("PrimaPag", "Istoric apeluri", nullptr));
        l_utilizatori_2->setText(QCoreApplication::translate("PrimaPag", "username utilizatori", nullptr));
        but_inf_2->setText(QCoreApplication::translate("PrimaPag", "Informatii utilizator", nullptr));
        but_stergere_2->setText(QCoreApplication::translate("PrimaPag", "Sterge utilizator", nullptr));
        tab_admin->setTabText(tab_admin->indexOf(utilizatori_2), QCoreApplication::translate("PrimaPag", "Utilizatori", nullptr));
        b_inf_disp->setText(QCoreApplication::translate("PrimaPag", "Informatii dispecer", nullptr));
        b_stergere_disp->setText(QCoreApplication::translate("PrimaPag", "Sterge dispecer", nullptr));
        b_add_disp->setText(QCoreApplication::translate("PrimaPag", "Adauga dispecer", nullptr));
        tab_admin->setTabText(tab_admin->indexOf(dispeceri), QCoreApplication::translate("PrimaPag", "Dispeceri", nullptr));
        inf_inrg->setText(QCoreApplication::translate("PrimaPag", "Informatii\n"
"inregistrare", nullptr));
        aprob_inrg->setText(QCoreApplication::translate("PrimaPag", "Aproba", nullptr));
        resping_inreg->setText(QCoreApplication::translate("PrimaPag", "Respinge", nullptr));
        tab_admin->setTabText(tab_admin->indexOf(cereri_inregistrari), QCoreApplication::translate("PrimaPag", "Inregistrari", nullptr));
        aprob_strg->setText(QCoreApplication::translate("PrimaPag", "Aproba", nullptr));
        resping_strg->setText(QCoreApplication::translate("PrimaPag", "Respinge", nullptr));
        inf_strg->setText(QCoreApplication::translate("PrimaPag", "Informatii\n"
"stergere", nullptr));
        tab_admin->setTabText(tab_admin->indexOf(cereri_stergeri), QCoreApplication::translate("PrimaPag", "Stergeri", nullptr));
        label_7->setText(QCoreApplication::translate("PrimaPag", "Administrator", nullptr));
        delog_adm->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class PrimaPag: public Ui_PrimaPag {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PRIMAPAG_H
